language: python
cache: pip
matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.6-7.3.1"
install:
  - "pip install ."
  - "pip install -r requirements_dev.txt"
script: py.test --cov haralyzer tests/ -vv
after_success:
  - coveralls
